Iter5
sourcecd/monitoring pull request #5
Opened 2024-04-05 14:11 UTC by sourcecd

2024-04-08 21:52 UTC, avhitrov requested changes
Гонки в данных на сервере + более мелкие замечания в комментариях к коду.

2024-04-08 21:52 UTC, avhitrov commented on internal/agent/agent.go
> +		fmt.Sprintf("%s/update/counter/pollcount/%d", serverHost, pollCount),
В задании название счетчика PollCount, кэмелкейсом. Остальные метрики - тоже. В таком виде их и следует передавать на сервер.

2024-04-08 21:52 UTC, avhitrov commented on internal/agent/agent.go
> +	if reportInterval > 0 && pollInterval > 0 && reportInterval > pollInterval {
Условия `reportInterval > pollInterval` в задании нет. Эти значения вполне могут быть равны друг другу. Да и вреда особого от того, что агент будет репортить чаще, чем собирает, тоже нет. Глупо, не не запрещено.

2024-04-08 21:52 UTC, avhitrov commented on internal/agent/agent.go
> +				}
Необходимо делать resp.Body.Close() в случае, если запрос отработал без ошибки. Иначе приложение будет течь по памяти. Можно либо обернуть всю процедуру осуществления запроса в безымянную функцию и в ней сделать `defer resp.Body.Close()`, либо включить эту строку здесь и внутри блока проверки статуса.

2024-04-08 21:52 UTC, avhitrov commented on internal/server/server.go
> +		}*/
Не следует оставлять в коде закомментированные блоки кода, это противоречит принципу систем хранения версий.

2024-04-08 21:52 UTC, avhitrov commented on internal/server/server.go
> +				http.Error(resp, "can't store gauge metric", http.StatusBadRequest)
Тут логичнее пятисотить. Эта ошибка явно связана с какой-то проблемой приложения, а не пользовательских действий.

2024-04-08 21:52 UTC, avhitrov commented on internal/storage/storage.go
> +	counter map[string]metrictypes.Counter
Мапы - структуры потоконебезопасные и в конкурентной среде (а http-сервер априори является конкурентным приложением, так как на каждый запрос пользователя хендлер открывается в отдельной горутине) должны защищаться блокировкой. Можно использовать либо sync.Mutex (sync.RWMutex), либо потокобезопасную мапу sync.Map.

https://t.me/bushigo/24

В данном случае имеем:
```
==================
WARNING: DATA RACE
Write at 0x00c00008aa80 by goroutine 185:
  runtime.mapassign_faststr()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  github.com/sourcecd/monitoring/internal/storage.(*MemStorage).WriteGauge()
      D:/work/src/github.com/sourcecd/monitoring/internal/storage/storage.go:25 +0x56
  github.com/sourcecd/monitoring/internal/server.chiRouter.updateMetrics.func1()
      D:/work/src/github.com/sourcecd/monitoring/internal/server/server.go:56 +0x1fe
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Previous read at 0x00c00008aa80 by goroutine 1582:
  runtime.mapiternext()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/runtime/map.go:867 +0x0
  github.com/sourcecd/monitoring/internal/storage.(*MemStorage).GetAllMetricsTxt()
      D:/work/src/github.com/sourcecd/monitoring/internal/storage/storage.go:50 +0x3b2
  github.com/sourcecd/monitoring/internal/server.chiRouter.getAll.func3()
      D:/work/src/github.com/sourcecd/monitoring/internal/server/server.go:125 +0x74
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Goroutine 185 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3239 +0x224
  github.com/sourcecd/monitoring/internal/server.Run()
      D:/work/src/github.com/sourcecd/monitoring/internal/server/server.go:143 +0x10e
  main.main()
      D:/work/src/github.com/sourcecd/monitoring/cmd/server/main.go:12 +0x44

Goroutine 1582 (running) created at:
  net/http.(*Server).Serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x86c
  net/http.(*Server).ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2985 +0xbc
  net/http.ListenAndServe()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3239 +0x224
  github.com/sourcecd/monitoring/internal/server.Run()
      D:/work/src/github.com/sourcecd/monitoring/internal/server/server.go:143 +0x10e
  main.main()
      D:/work/src/github.com/sourcecd/monitoring/cmd/server/main.go:12 +0x44
==================
==================
WARNING: DATA RACE
Write at 0x00c0000c0b98 by goroutine 185:
  github.com/sourcecd/monitoring/internal/storage.(*MemStorage).WriteGauge()
      D:/work/src/github.com/sourcecd/monitoring/internal/storage/storage.go:25 +0x64
  github.com/sourcecd/monitoring/internal/server.chiRouter.updateMetrics.func1()
      D:/work/src/github.com/sourcecd/monitoring/internal/server/server.go:56 +0x1fe
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve.func3()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:3086 +0x4f

Previous read at 0x00c0000c0b98 by goroutine 1582:
  github.com/sourcecd/monitoring/internal/storage.(*MemStorage).GetAllMetricsTxt()
      D:/work/src/github.com/sourcecd/monitoring/internal/storage/storage.go:50 +0x2b2
  github.com/sourcecd/monitoring/internal/server.chiRouter.getAll.func3()
      D:/work/src/github.com/sourcecd/monitoring/internal/server/server.go:125 +0x74
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x544
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2136 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x67b
  net/http.serverHandler.ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2938 +0x2a1
  net/http.(*conn).serve()
      C:/Users/ahitrov/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.8.windows-amd64/src/net/http/server.go:2009 +0xc24
  net/http.(*Server).Serve. [...]

2024-04-09 08:29 UTC, sourcecd commented on internal/agent/agent.go
> +				}
resty автоматически закрывает body, насколько я понял.

2024-04-09 09:43 UTC, sourcecd commented on internal/server/server.go
> +				http.Error(resp, "can't store gauge metric", http.StatusBadRequest)
поставил StatusInternalServerError

2024-04-09 09:52 UTC, sourcecd commented on internal/storage/storage.go
> +	counter map[string]metrictypes.Counter
fixed

2024-04-11 20:08 UTC, avhitrov approved these changes
Все ок. На будущее прошу не резолвить мои комментарии, я это делаю сам по мере проверки устранения проблем.

2024-04-11 20:11 UTC, sourcecd commented
понял, хорошо, спасибо

2024-04-11 20:11 UTC, merged